-- Created:  Fri 09 Nov 2018
-- Modified: Fri 09 Nov 2018
-- Author:   Josh Wainwright
-- Filename: mappings.lua
return {
	['Billy_Joel_-_Best_Of_Solo_Piano.pdf'] = {
		"2,All About Soul",
		"7,Allentown",
		"11,And So It Goes",
		"14,Baby Grand",
		"19,Honesty",
		"22,An Innocent Man",
		"26,It's Still Rock and Roll to Me",
		"30,Just the Way You Are",
		"33,Keeping the Faith",
		"37,The Longest Time",
		"39,My Life",
		"43,Only the Good Die Young",
		"49,Piano Man",
		"54,The River of Dreams",
		"58,She's Always a Woman",
		"63,She's Got a Way",
		"66,Tell Her About it",
		"70,Uptown Girl",
		"73,We Didn't Start the Fire",
	},
	['Keith_Getty_-_Getty_Hymns.pdf'] = {
		"4,Across the Lands",
		"6,Behold the Lamb (The Communion Hymn)",
		"8,Beneath the Cross",
		"10,Benediction (May the Peace)",
		"12,Come, People of the Risen King",
		"14,Compassion Hymn (There is an Everlasting Kindness)",
		"16,Creation Sings",
		"18,Every Promise (From the Breaking of the Dawn)",
		"20,Father We Have Sinned (Repentance)",
		"21,God of Grace",
		"22,Glorious Light",
		"24,Hear All Creation",
		"26,Hear The Call Of The Kingdom",
		"28,Holy Child",
		"30,Holy Spirit",
		"32,In Christ Alone",
		"34,Jesus, Draw Me Ever Nearer",
		"35,Jesus, Your Name",
		"36,Jesus is Lord",
		"38,Joy Has Dawned",
		"40,King of the Ages",
		"42,Let the Earth Resound",
		"44,Light of God",
		"46,Lord, We Wait",
		"48,Love of God",
		"50,Merciful God",
		"52,My Heart is Filled With Thankfulness",
		"54,My Hope Rests Firm",
		"56,O Church, Arise",
		"58,One Church, One Faith (Your Hand, O God, Has Guided)",
		"60,See, What a Morning (Resurrection Hymn)",
		"62,Speak, O Lord",
		"64,Spirit Of Heaven",
		"66,The Power of the Cross (O, to See the Dawn)",
		"68,The Risen Christ (O Breath of God)",
		"70,There is a Higher Throne",
		"72,When Trials Come",
	},
	['Keith_Getty_-_In_Christ_Alone_Album.pdf'] = {
		"2,There Is a Higher Throne",
		"4,Across the Lands",
		"6,Jesus, Draw Me Ever Nearer",
		"8,Hear the Call of the Kingdom",
		"10,The Power of the Cross",
		"12,Beneath the Cross",
		"14,In Christ Alone",
		"16,See, What a Morning (Resurrection Hymn)",
		"18,Speak, O Lord",
		"20,O Church, Arise",
		"22,Don't Let Me Loose My Wonder",
	},
	['Hugh_Laurie_-_St_James_Infirmary.pdf'] = {
		"1,St. James Infirmary",
		"8,You Don't Know My Mind",
		"15,Buddy Bolden's Blues",
		"18,Six Cold Feet",
		"22,Battle of Jericho",
		"29,Swanee River",
		"34,After You've Gone",
		"40,The Whale Has Swallowed Me",
		"45,Baby, Please Make a Change",
		"50,John Henry",
		"54,Police Dog Blues",
		"58,Tipitina",
		"64,Winin' Boy Blues",
		"68,They're Red Hot",
		"72,Let Them Talk",
	},
	['Simon_and_Garfunkel_-_Greatest_Hits.pdf'] = {
		"1,Mrs. Robinson",
		"8,For Emily, Whenever I May Find Her",
		"12,The Boxer",
		"20,The 59th Street Bridge Song",
		"23,The Sound of Silence",
		"28,I Am A Rock",
		"30,Scarborough Fair/Canticle",
		"34,Homeward Bound",
		"37,Bridge Over Troubled Water",
		"42,America",
		"50,Kathy's Song",
		"55,Bookends",
		"57,Cecilia",
	},
}
